#remote_theme: pages-themes/leap-day@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
title: Workshop on Algebraic Geometry and Complex Geometry in Osaka

# description: Around positivity of tangent sheaves and anti-canonical divisors
#theme: jekyll-theme-cayman

# 画像と動作設定（必要に応じて差し替え）
header_image: /assets/img/osaka-castle.jpg   # JS無効時のデフォルト
header_images:
  - /assets/img/osaka-castle.jpg
  - /assets/img/nakanoshima.jpg
  - /assets/img/tsutenkaku.jpg
  - /assets/img/dotonbori.jpg
overlay_opacity: 0.35
rotate_interval_ms: 8000

# 既存の設定はそのまま
header_max_width: 1200px   # ←ヘッダー内テキストの横幅を広げる
header_height: 3.2rem      # ←上下余白を減らして縦幅を少し小さく（好みで）
header_min_height: 26vh    # ←最低高さ（もう少し小さくしたければ 22vh など）
content_max_width: 1200px  # ←本文側も広くしたい場合（任意）
